# Generated by Django 2.2.16 on 2020-10-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_contact'),
    ]

    operations = [
    ]
